modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "extralib"
version = "1.5.1"
displayName = "ExtraLib"
logoFile = "logo.png"
authors = "Vecoo"
description = "Library for mods."

[[dependencies.extralib]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extralib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"