modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="extrasapi"
version="1.1.0"
displayName="ExtrasAPI"
authors="Vecoo"
description="API for various mods."

[[dependencies.extrasapi]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.extrasapi]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="BOTH"