modLoader="javafml"
loaderVersion="[48,)"
license="All Rights Reserved"

[[mods]]
modId="extralib"
version="1.2.2"
displayName="ExtraLib"
logoFile ="logo.png"
authors="Vecoo"
description="Library for various mods."

[[dependencies.extralib]]
modId="forge"
mandatory=true
versionRange="[48.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.extralib]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"